name: React Native Build & Release
on:
  pull_request_review:
    types: [submitted]
    branches:
      - dev
    if: github.event.review.state == 'approved'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
         distribution: "temurin"
         java-version: 17

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

  
      - name: Run Android Release Build
        run: |
          cd android
          ./gradlew assembleRelease
      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Notify Release
        run: |
          echo "Build artifact for Android is uploaded"
